development:
  adapter: postgresql
  database: nomoresheets
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: nomoresheets
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: nomoresheets
  pool: 5
  timeout: 5000
